const path = {
  home: '/',
  login: '/login',
  register: '/register',
  member: '/member',
  admin: '/admin',
  shop: '/shop',
  email: '/email',
  policy: '/policy',
  otp: '/otp',
  resetPassword: '/resetPassword',
  verify: '/api/verifyEmail',
  verifySuccess: '/verify',
  myAccount: '/member/myAccount',
  profile: '/member/myAccount/profile',
  shopCart: '/member/myAccount/shopCart',
  dashboard: '/member/dashboard',
  myKoi: '/member/myKoi',
  pricing: '/member/pricing',
  myPond: '/member/myPond',
  waterParameters: '/member/waterParameters',
  reminders: '/member/reminders',
  recommendations: '/member/recommendations',
  foodCalculator: '/member/foodCalculator',
  saltCalculator: '/member/saltCalculator',
  statistics: '/member/statistics',
  news: '/member/news',
  payment: '/member/payment',
  paymentSuccess: '/member/paymentSuccess',
  paymentError: '/member/paymentError',
  newsDetails: '/member/news/:id',
  koiDetail: '/member/myKoi/:id',
  recommendationDetail: '/member/recommendations/:id',
  aboutMember: '/member/about',
  myPondLog: '/member/myPond/myPondLog',
  myPondLogDetail: '/member/myPond/myPondLog/:id',
  myPondIssue: '/member/myPond/myPondIssue/:id',
  shopNews: '/shop/shopNews',
  createNews: '/shop/createNews',
  updateNews: '/shop/shopNews/update/:id',
  viewNews: '/shop/shopNews/:id',
  tag: '/shop/tag',
  createTag: '/shop/createTag',
  updateTag: '/shop/tag/:id',
  supplier: '/shop/supplier',
  createSupplier: '/shop/createSupplier',
  updateSupplier: '/shop/supplier/:id',
  checkout: '/member/checkout',
  wishList: '/member/wishList',
  cartList: '/member/cartList',
  promotion: '/shop/promotion',
  createPromotion: '/shop/createPromotion',
  updatePromotion: '/shop/promotion/:id',
  product: '/shop/product',
  createProduct: '/shop/createProduct',
  updateProduct: '/shop/product/:id',
  viewProduct: 'shop/product/view/:id',
  category: '/shop/category',
  createCategory: '/shop/createCategory',
  updateCategory: '/shop/category/:id',
  promotionAD: '/admin/promotion',
  productImage: '/shop/productImage',
  createImage: '/shop/createImage',
  updateImage: '/shop/productImage/:id',
  viewUser: '/shop/viewUser',
  shopAD: '/admin/shop',
  customerAD:'/admin/user',
  viewUserAD:'/admin/user/:id',

  userDetail: '/shop/viewUser/:id',
  paymentShop: '/shop/payment',
  orderShop: '/shop/order',
  dashboardShop: '/shop/dashboard',
  profileShop:'/shop/profileShop'
}

export default path
