const path = {
  home: '/',
  login: '/login',
  register: '/register',
  member: '/member',
  admin: '/admin',
  shop: '/shop',
  email: '/email',
  otp: '/otp',
  resetPassword: '/resetPassword',
  verify: '/verifyPending',
  verifySuccess: '/verify',
  myAccount: '/member/myAccount',
  profile: '/member/myAccount/profile',
  shopCart: '/member/myAccount/shopCart',
  dashboard: '/member/dashboard',
  myKoi: '/member/myKoi',
  myPond: '/member/myPond',
  waterParameters: '/member/waterParameters',
  reminders: '/member/reminders',
  recommendations: '/member/recommendations',
  foodCalculator: '/member/foodCalculator',
  saltCalculator: '/member/saltCalculator',
  statistics: '/member/statistics',
  news: '/member/news',
  policy: '/policy',
  newsDetails: '/member/news/:id',
  koiDetail: '/member/myKoi/:id'
}

export default path
